policy_base_url: ${oc.env:NVIDIA_INFERENCE_BASE_URL,https://inference-api.nvidia.com/v1}
policy_api_key: ${oc.env:NVIDIA_API_KEY}
policy_model_name: ${oc.env:NVIDIA_INFERENCE_MODEL,nvidia/eccn-nemotron-3-ultra}

policy_model:
  responses_api_models:
    vllm_model:
      entrypoint: app.py
      base_url: ${policy_base_url}
      api_key: ${policy_api_key}
      model: ${policy_model_name}
      return_token_id_information: false
      uses_reasoning_parser: true
      uses_interleaved_reasoning: true
      chat_template_kwargs: null
      extra_body:
        cache:
          no-cache: true
      default_headers: {}
